dist: trusty
sudo: false
language: go
go:
  - "1.11"
env:
  global:
    - GO111MODULE=on
    - PATH=$PATH:$GOPATH/bin
    - GOLANGCILINT=v1.10.2
install:
  - go build
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin $GOLANGCILINT
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - golangci-lint run
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload.'
